[package]
name = "clip_stash"
version = "0.1.0"
edition = "2021"

[lib]
name = "clip_stash"
path = "src/lib/mod.rs"

[dependencies]
serde = "1"
serde_json = "1"
thiserror = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
